ALTER TABLE GAMEPLAYS ADD CONSTRAINT gameplays_description_unique UNIQUE(description);

INSERT INTO GAMEPLAYS (ID_GAMEPLAY, TYPE, DESCRIPTION) VALUES (GAMEPLAYS_SEQ.NEXTVAL, 'T', 'Tournament');
INSERT INTO GAMEPLAYS (ID_GAMEPLAY, TYPE, DESCRIPTION) VALUES (GAMEPLAYS_SEQ.NEXTVAL, 'S', 'Single Matche');


--- ROLLBACK ---
ALTER TABLE GAMEPLAYS drop CONSTRAINT gameplays_description_unique;

DELETE GAMEPLAYS WHERE DESCRIPTION = 'Tournament';
DELETE GAMEPLAYS WHERE DESCRIPTION = 'Single Matche';